[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/auth/tiktok/callback"
  to = "/api/auth/callback"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://*.tiktokcdn.com; script-src 'self' https://www.tiktok.com; style-src 'self' 'unsafe-inline'; frame-src https://www.tiktok.com"