[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[headers]]
for = "/*"
  [headers.values]
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Content-Security-Policy = """
    default-src 'self';
    base-uri 'self';
    img-src 'self' data: blob: https://*.tiktokcdn.com https://*.tiktokcdn-eu.com https://*.tiktok.com https://*.mapbox.com https://api.mapbox.com;
    media-src 'self' blob: data:;
    font-src 'self' data:;
    script-src 'self' https://www.tiktok.com https://*.tiktok.com https://api.mapbox.com;
    style-src 'self' 'unsafe-inline' https://api.mapbox.com;
    frame-src https://www.tiktok.com https://*.tiktok.com;
    connect-src 'self'
      https://open.tiktokapis.com
      https://open-api.tiktokglobalplatform.com
      https://www.tiktok.com https://*.tiktok.com
      https://*.tiktokcdn.com https://*.tiktokcdn-eu.com
      https://api.mapbox.com https://events.mapbox.com;
  """